### ISSUE TITLE
Isn't injected into UserDefinedForm pages

### ISSUE THREAD

**Issue by purplespider** [jonom/silverstripe-betternavigator#47]
Better Navigator doesn't currently seem to work on `UserDefinedForm` pages. 

Looks like the `instance of DBHTMLText` check is failing on these pages, so the HTML isn't getting injected:
https://github.com/jonom/silverstripe-betternavigator/blob/master/src/Extension/BetterNavigatorExtension.php#L54

That's as far as I managed to get in debugging it!

**Comment by jonom** [comment]
Hi @purplespider looks like #46 is related. I pushed up a fix a while ago (tweaked it this morning) that I think should help you - would you be able to try [this branch](https://github.com/jonom/silverstripe-betternavigator/tree/fix-46) and report back if it solves the problem for you?

**Comment by purplespider** [comment]
Thanks, Jono. just tried the fix-46 branch, and while you no longer get a JS error in the console on User Form pages, Better Navigator still doesn't appear. Displays on other pages fine.

_Tested on fresh Silverstripe 4.6.0 and latest UserForms 5.6.0._

**Comment by jonom** [comment]
Interesting. I don't use UserForms myself so I may not get a chance to debug this further for now, sorry. If you're able to look in to it more let me know what you find!

**Comment by jonom** [comment]
I went further down the rabbit hole this morning. Problem seems to be that the result of Controller::handleAction() can be all kinds of things, including a Controller (API says only `DBHTMLText|HTTPResponse` but not true). This is accounted for later in the pipeline - `Controller::handleRequest()` calls `Controller::prepareResponse` which is responsible for rendering Controllers and things out to HTML. I guess we could replicate that functionality within BetterNavigatorExtension but it feels like overkill and probably doubles render effort.

The API documentation is pretty far off here, like RequestHandler::handleAction() says they only thing it can return is a HTTPResponse, but that conflicts with reality and [comments in the code](https://github.com/silverstripe/silverstripe-framework/blob/237b2d5f74c20bb507a94a48f5c30a95c20525cf/src/Control/Controller.php#L212-L215).

I don't see an extension point we can use at an appropriate point in the response pipeline to solve this issue but maybe there's a middleware we can use to check for a HTML response really late in the pipeline? @unclecheese would really value your input here. (Side note: this is why I insisted on tagging a major release for that [seemingly innocent change](https://github.com/jonom/silverstripe-betternavigator/pull/43) 😅)

@purplespider can you please try installing v4 instead of v5 and see if that fixes the problem for you. You'll need to put `$BetterNavigator` in your main page template but otherwise it's almost the same as v5.

**Comment by jonom** [comment]
@purplespider possibly just changing UserForms to render the result would fix the issue for you. Change [this part](https://github.com/silverstripe/silverstripe-userforms/blob/53e4ba079f682bcd8db9be97f9bcb0e7adf3f9b4/code/Control/UserDefinedFormController.php#L142-L145) to

```
return $this->render([
    'Content' => DBField::create_field('HTMLText', $this->Content),
    'Form' => $this->Form()
]);
```

I guess that would probably constitute a breaking change though 🤷

**Comment by purplespider** [comment]
Thanks for looking into this further, Jono.

> @purplespider can you please try installing v4 instead of v5 and see if that fixes the problem for you. You'll need to put `$BetterNavigator` in your main page template but otherwise it's almost the same as v5.

Yep, I can confirm that v4 works fine on UserForms pages.

> @purplespider possibly just changing UserForms to render the result would fix the issue for you. Change [this part](https://github.com/silverstripe/silverstripe-userforms/blob/53e4ba079f682bcd8db9be97f9bcb0e7adf3f9b4/code/Control/UserDefinedFormController.php#L142-L145) to
> 
> ```
> return $this->render([
>     'Content' => DBField::create_field('HTMLText', $this->Content),
>     'Form' => $this->Form()
> ]);
> ```
> 
> I guess that would probably constitute a breaking change though 🤷

Yep, this makes v5 work!

**Comment by jonom** [comment]
I think the solution for this is going to be re-adding support for `$BetterNavigator` in templates, but making it optional, so sites that are affected by this issue (e.g. any using UserForms) have a way to fix it, but otherwise it's unnecessary.

In the `afterCallActionHandler` we can probably do a simple `strpos` test to see if the BetterNavigator HTML or script has already been added, and skip adding it again if so.

**Comment by purplespider** [comment]
That sounds sensible to me, Jono! Thanks.
